name: flame_example
description: Simple example of a Flame game
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flame: ^1.8.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.0.0
  flutter_test:
    sdk: flutter
